### ISSUE TITLE
Stopped working with version 25

### ISSUE THREAD

**Issue by My-Random-Thoughts** [OliverParoczai/nextcloud-unroundedcorners#10]
Hello, not sure if you have had a chance to look at NC25 - only came out yesterday, but your wonderful CSS has stopped working.
I have had a quick look and all the CSS classes are still called the same so I am not sure why.

**Comment by OliverParoczai** [comment]
Hello!

Thank you for letting me know of the problem. I didn't update to NC 25 yet, or even knew that it had already come out. At first it looks like I will only need to bump the supported version number, but I be able to know more when my NC instance finishes the upgrade process.

I will keep this thread updated as things happen :)

Thanks again for your support,
Oliver

**Comment by My-Random-Thoughts** [comment]
Awesome, thank you.  
Initial tests of overwriting my current css file with your changed ones looks very good.

**Comment by crdxfire** [comment]
<img width="368" alt="image" src="https://user-images.githubusercontent.com/63368841/197174502-b3d0fa3b-bb66-4c5c-b021-002b1eb37001.png">
Talk is not working - the bottom edge of the screen for entering text is hidden

**Comment by NadeoGolf** [comment]
> <img alt="image" width="368" src="https://user-images.githubusercontent.com/63368841/197174502-b3d0fa3b-bb66-4c5c-b021-002b1eb37001.png">
> Talk is not working - the bottom edge of the screen for entering text is hidden

I have the same issue.

**Comment by OliverParoczai** [comment]
Hello! Thanks for clarifying the problem, working on it! ETA a few hours

**Comment by NadeoGolf** [comment]
After a cache refresh, i have a other issue:

![image](https://user-images.githubusercontent.com/62070654/197188672-af106f52-2445-4d92-8e08-0fa47894a631.png)

**Comment by OliverParoczai** [comment]
Hello!

Made the necessary changes to the CSS, it should work now. Please check out PR #12 and #13, if there are any problems let me know.

The update (v1.0.5) is already live on the NC app store, but will need some time for the instances to cache the new app versions (usually around 30 minutes)

**Comment by NadeoGolf** [comment]
Thanks for the update but I have a issue on other apps:

With your application:

![image](https://user-images.githubusercontent.com/62070654/197208556-404e5683-41e7-4388-a66d-8beecce0bb34.png)

Without:

![image](https://user-images.githubusercontent.com/62070654/197209003-6f65d303-2697-4724-bd0c-6404acf20f3c.png)

**Comment by OliverParoczai** [comment]
Hello.

Just got home. Looks like most of the problems (including the hidden chat menu in Talk) stemmed from hardcoding the content body height, which would have been fine if left to it's original setting. Pushing the update now, it will go live in about half a hour. Let me know if there are any other problems or incompatibilities with other plugins, I will be available to fix them.

Thank you all for your support,
Oliver

**Comment by NadeoGolf** [comment]
Everything seems ok, thank you for your reactivity and your support :)
