### ISSUE TITLE
not working in NC 24.0.6

### ISSUE THREAD

**Issue by nousernameavailableanymore** [OliverParoczai/nextcloud-unroundedcorners#15]
Worked fine in 24.0.5
Not working anymore since update to 24.0.6
![image](https://user-images.githubusercontent.com/45376324/197317817-15ff4afc-84dc-40ae-a66d-0560058ed97d.png)

**Comment by OliverParoczai** [comment]
Hello!

Sorry for the late reply, the problem wasn't because of the update to 24.0.6, just a coincidence. I upgraded the code to support NC 25 yesterday that changed a lot of variables, and your client downloaded the new, incompatible version when updating. Essentially it was because of a problem with tagging supported versions.

The compatibility release should be available now. In about 30 minutes it will be picked up by the app update checker, and will be installable. Let me know if you experience any problems.

Thanks  for your support,
Oliver

**Comment by 735trv** [comment]
Hi @OliverParoczai,

I found a few elements which are not rounded. I'm not sure if the elements were round before as well or if this is related to this issue.

I have attached the elements as a screenshot. These are all the "official" apps. The filename matches the area inside Nextcloud where I discovered it. If you need more information, I'm happy to help. :slightly_smiling_face: 

Nextcloud Version: v26.0.6
Unrounded Corners: v1.0.6

- [apps.png](https://user-images.githubusercontent.com/89764058/197457764-78bc38d1-964b-4966-90ec-be4b611fc5b9.png)
- [calendar_1.png](https://user-images.githubusercontent.com/89764058/197457765-5d3f2fe6-5835-4acd-8f82-aad98450c4eb.png)
- [calendar_2.png](https://user-images.githubusercontent.com/89764058/197457766-38cefb43-1e88-4a9d-bdd6-70f062ca1357.png)
- [calendar_3.png](https://user-images.githubusercontent.com/89764058/197457768-3d137aa4-893a-454e-9d00-726cb1e2e70c.png)
- [contacts_1.png](https://user-images.githubusercontent.com/89764058/197457771-a41176a5-fc78-47c7-aecd-d14e15dc024c.png)
- [contacts_2.png](https://user-images.githubusercontent.com/89764058/197457777-86274176-8788-4a26-ac5c-9441d7e386cd.png)
- [users_1.png](https://user-images.githubusercontent.com/89764058/197457780-2456bfc0-a728-4cb6-80e2-c9b9dc796766.png)
- [users_2.png](https://user-images.githubusercontent.com/89764058/197457783-8597c487-1947-4396-b605-ed13983a496d.png)

**Comment by OliverParoczai** [comment]
Hello!

Thanks for the reply, please try reinstalling the extension. I believe the wrong (NC25) version got accidentally pushed out to NC 24 users who upgraded their apps in the last 2 or 3 days

If you remove the extension and reinstall it, it should be on version 1.0.3, the last version made for NC24

Sorry for the trouble and thanks for your support,
Oliver

**Comment by 735trv** [comment]
Ah okay. Thank you Oliver for the explanation. That worked. :+1: :+1: 

Thanks for your work. Absolutely a must have app! :blush:

**Comment by OliverParoczai** [comment]
Thank you! :)
If you have any other problems or questions, let me know!
