### ISSUE TITLE
Not working under NC25

### ISSUE THREAD

**Issue by seabokas** [OliverParoczai/nextcloud-unroundedcorners#17]
Sorry, but the Plugin made the styles even worst.

**Enabled Plugin**
![mailapp](https://user-images.githubusercontent.com/1898635/203611222-fa57633f-8d0f-4dd3-95c5-0c128458a564.JPG)

**Disabled Plugin**
![mailapp-without](https://user-images.githubusercontent.com/1898635/203611248-35604ec1-102b-4fec-91c7-b8ab9f5e9eab.JPG)

NextCloud 25.0.1
Mail	2.1.2
Unrounded Corners 1.0.6

**Comment by OliverParoczai** [comment]
Hello! Sorry for the late reply, I wasn't near a computer for some time.

I have upgraded my NC instance to the same version as you are on, and couldn't find the problem for a few minutes, but found out that the NC devs decided that the system theme should use a different CSS class than the light and dark variants, so the upgrade will go live in a few hours to address this.

Please wait about half an hour after the update is live for it to be shown on your NC instance's plugins page, as it maintains a cache.

Let me know if there are any problems, I will be happy to fix them as soon as they are discovered.

Thanks,
Oliver

**Comment by OliverParoczai** [comment]
PR #18 fixed the problem, and the update is already live, just need to wait out the caching period now.

Thanks again for your support,
Oliver

**Comment by seabokas** [comment]
Thanks Oliver.
