### ISSUE TITLE
wrong display when Unround is active

### ISSUE THREAD

**Issue by punkyard** [OliverParoczai/nextcloud-unroundedcorners#24]
Hi
I really appreciate this app that brings back more space to the NC interface
But when activated, addressbooks are truncated in the contact app

<img width="506" alt="Capture d’écran 2023-10-09 à 09 24 39" src="https://github.com/OliverParoczai/nextcloud-unroundedcorners/assets/59349105/4bb2e240-1ad4-4022-9771-983180e6f878">

but they are not when Unround corners is deactivated

<img width="793" alt="Capture d’écran 2023-10-09 à 09 42 10" src="https://github.com/OliverParoczai/nextcloud-unroundedcorners/assets/59349105/d4769c76-d661-43bf-8f2e-6ffb1bb74978">

could you have a look please?
thanks

**Comment by OliverParoczai** [comment]
Hello! Thank you for reporting this issue, I will be looking into it. Could I ask which NC version you are using?

**Comment by OliverParoczai** [comment]
Pushed an update out with the fix in PR #25, the update will be out on the NC App Store in about 8 hours, let me know if it fixes things.
